# Generated by Django 4.2 on 2025-09-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_calificacion_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, unique=True),
        ),
    ]
