# Generated by Django 5.2.7 on 2025-10-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante_id', models.IntegerField()),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nivel_riesgo', models.CharField(default='Bajo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante_id', models.IntegerField()),
                ('curso_id', models.IntegerField()),
                ('nota', models.FloatField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral_bajo', models.FloatField(default=3.0)),
                ('umbral_medio', models.FloatField(default=4.0)),
                ('frecuencia_alertas', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal')], default='semanal', max_length=50)),
                ('criterios_recomendacion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Configuraciones del Agente',
            },
        ),
    ]
