# Generated by Django 4.2 on 2025-09-08 00:44

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]
    operations = [
        migrations.CreateModel(
            name='ConfigAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('umbral_bajo', models.FloatField(default=3.0)),
                ('umbral_medio', models.FloatField(default=4.0)),
                ('frecuencia_alertas', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal')], default='semanal', max_length=50)),
                ('criterios_recomendacion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Configuraciones del Agente',
            },
        ),
    ]
