# Generated by Django 4.2 on 2025-09-08 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_email'),
        ('app', '0003_configagente'),
    ]

    operations = [
    ]
