# Generated by Django 4.2 on 2025-09-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_0002_alter_customuser_email_0003_configagente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configagente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
