# Generated by Django 4.2 on 2025-10-14 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_estudiante_cursos'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
